import { Button } from "@/components/ui/button";
import { Download, Loader2 } from "lucide-react";
import { useState } from "react";
import { toast } from "@/hooks/use-toast";

interface DisputePdfExportProps {
  letterContent: string;
  creditorName: string;
  bureau: string;
  disputeId: string;
  className?: string;
}

export function DisputePdfExport({
  letterContent,
  creditorName,
  bureau,
  disputeId,
  className,
}: DisputePdfExportProps) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      // Build a styled HTML document for print-to-PDF
      const printContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Dispute Letter - ${creditorName}</title>
  <style>
    @media print {
      @page { margin: 1in; size: letter; }
    }
    body {
      font-family: 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #111;
      max-width: 7.5in;
      margin: 0 auto;
      padding: 1in;
    }
    .header {
      text-align: center;
      margin-bottom: 2em;
      padding-bottom: 1em;
      border-bottom: 2px solid #b8860b;
    }
    .header h1 {
      font-size: 16pt;
      color: #b8860b;
      margin: 0 0 4px;
    }
    .header p {
      font-size: 10pt;
      color: #666;
      margin: 0;
    }
    .meta {
      display: flex;
      justify-content: space-between;
      margin-bottom: 2em;
      font-size: 10pt;
      color: #555;
    }
    .content {
      white-space: pre-wrap;
      font-size: 12pt;
    }
    .footer {
      margin-top: 3em;
      padding-top: 1em;
      border-top: 1px solid #ddd;
      font-size: 9pt;
      color: #888;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>DISPUTE LETTER</h1>
    <p>Generated by Lion's Wealth Engine — FCRA Compliant</p>
  </div>
  <div class="meta">
    <div>
      <strong>Bureau:</strong> ${bureau}<br />
      <strong>Creditor:</strong> ${creditorName}
    </div>
    <div>
      <strong>Date:</strong> ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}<br />
      <strong>Ref:</strong> ${disputeId.slice(0, 8).toUpperCase()}
    </div>
  </div>
  <div class="content">${letterContent.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
  <div class="footer">
    This letter was generated in compliance with the Fair Credit Reporting Act (FCRA).
    &copy; ${new Date().getFullYear()} Lion's Wealth Engine
  </div>
</body>
</html>`;

      const printWindow = window.open("", "_blank");
      if (!printWindow) {
        toast({
          title: "Popup blocked",
          description: "Please allow popups for this site to export PDFs.",
          variant: "destructive",
        });
        return;
      }

      printWindow.document.write(printContent);
      printWindow.document.close();

      // Wait for content to render then trigger print
      printWindow.onload = () => {
        printWindow.print();
      };

      // Fallback if onload doesn't fire
      setTimeout(() => {
        printWindow.print();
      }, 500);

      toast({
        title: "PDF ready",
        description: "Use your browser's Save as PDF option in the print dialog.",
      });
    } catch (error) {
      toast({
        title: "Export failed",
        description: "Could not generate the PDF. Please try again.",
        variant: "destructive",
      });
    } finally {
      setExporting(false);
    }
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleExport}
      disabled={exporting || !letterContent}
      className={className}
    >
      {exporting ? (
        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
      ) : (
        <Download className="w-4 h-4 mr-2" />
      )}
      Export PDF
    </Button>
  );
}
